
export enum UserRole {
  TEACHER = 'TEACHER',
  STUDENT = 'STUDENT'
}

export enum UserStatus {
  MUTED = 'MUTED',
  HAND_RAISED = 'HAND_RAISED',
  SPEAKING = 'SPEAKING',
  PTT_HOLDING = 'PTT_HOLDING'
}

export interface Participant {
  id: string;
  name: string;
  role: UserRole;
  language: string;
  status: UserStatus;
  avatar: string;
  gender?: string;
}

export interface Message {
  id: string;
  senderId: string;
  senderName: string;
  originalText: string;
  translatedText?: string;
  sourceLanguage?: string;
  timestamp: number;
}

export const LANGUAGES = [
  { code: 'Dutch Flemish', name: 'Dutch Flemish' },
  { code: 'Abkhaz', name: 'Abkhaz' },
  { code: 'Acehnese', name: 'Acehnese' },
  { code: 'Acholi', name: 'Acholi' },
  { code: 'Afar', name: 'Afar' },
  { code: 'Afrikaans', name: 'Afrikaans' },
  { code: 'Albanian', name: 'Albanian' },
  { code: 'Alur', name: 'Alur' },
  { code: 'Amharic', name: 'Amharic' },
  { code: 'Arabic', name: 'Arabic' },
  { code: 'Armenian', name: 'Armenian' },
  { code: 'Assamese', name: 'Assamese' },
  { code: 'Avar', name: 'Avar' },
  { code: 'Awadhi', name: 'Awadhi' },
  { code: 'Aymara', name: 'Aymara' },
  { code: 'Azerbaijani', name: 'Azerbaijani' },
  { code: 'Balinese', name: 'Balinese' },
  { code: 'Baluchi', name: 'Baluchi' },
  { code: 'Bambara', name: 'Bambara' },
  { code: 'Baoulé', name: 'Baoulé' },
  { code: 'Bashkir', name: 'Bashkir' },
  { code: 'Basque', name: 'Basque' },
  { code: 'Batak Karo', name: 'Batak Karo' },
  { code: 'Batak Simalungun', name: 'Batak Simalungun' },
  { code: 'Batak Toba', name: 'Batak Toba' },
  { code: 'Belarusian', name: 'Belarusian' },
  { code: 'Bemba', name: 'Bemba' },
  { code: 'Bengali', name: 'Bengali' },
  { code: 'Betawi', name: 'Betawi' },
  { code: 'Bhojpuri', name: 'Bhojpuri' },
  { code: 'Bikol', name: 'Bikol' },
  { code: 'Bosnian', name: 'Bosnian' },
  { code: 'Breton', name: 'Breton' },
  { code: 'Bulgarian', name: 'Bulgarian' },
  { code: 'Buryat', name: 'Buryat' },
  { code: 'Cantonese', name: 'Cantonese' },
  { code: 'Catalan', name: 'Catalan' },
  { code: 'Cebuano', name: 'Cebuano' },
  { code: 'Chamorro', name: 'Chamorro' },
  { code: 'Chechen', name: 'Chechen' },
  { code: 'Chichewa', name: 'Chichewa' },
  { code: 'Chinese (Simplified)', name: 'Chinese (Simplified)' },
  { code: 'Chinese (Traditional)', name: 'Chinese (Traditional)' },
  { code: 'Chuukese', name: 'Chuukese' },
  { code: 'Chuvash', name: 'Chuvash' },
  { code: 'Corsican', name: 'Corsican' },
  { code: 'Crimean Tatar (Cyrillic)', name: 'Crimean Tatar (Cyrillic)' },
  { code: 'Crimean Tatar (Latin)', name: 'Crimean Tatar (Latin)' },
  { code: 'Croatian', name: 'Croatian' },
  { code: 'Czech', name: 'Czech' },
  { code: 'Danish', name: 'Danish' },
  { code: 'Dari', name: 'Dari' },
  { code: 'Dhivehi', name: 'Dhivehi' },
  { code: 'Dinka', name: 'Dinka' },
  { code: 'Dogri', name: 'Dogri' },
  { code: 'Dombe', name: 'Dombe' },
  { code: 'Dutch', name: 'Dutch' },
  { code: 'Dyula', name: 'Dyula' },
  { code: 'Dzongkha', name: 'Dzongkha' },
  { code: 'English', name: 'English' },
  { code: 'Esperanto', name: 'Esperanto' },
  { code: 'Estonian', name: 'Estonian' },
  { code: 'Ewe', name: 'Ewe' },
  { code: 'Faroese', name: 'Faroese' },
  { code: 'Fijian', name: 'Fijian' },
  { code: 'Filipino', name: 'Filipino' },
  { code: 'Finnish', name: 'Finnish' },
  { code: 'Fon', name: 'Fon' },
  { code: 'French', name: 'French' },
  { code: 'French (Canada)', name: 'French (Canada)' },
  { code: 'Frisian', name: 'Frisian' },
  { code: 'Friulian', name: 'Friulian' },
  { code: 'Fulani', name: 'Fulani' },
  { code: 'Ga', name: 'Ga' },
  { code: 'Galician', name: 'Galician' },
  { code: 'Georgian', name: 'Georgian' },
  { code: 'German', name: 'German' },
  { code: 'Greek', name: 'Greek' },
  { code: 'Guarani', name: 'Guarani' },
  { code: 'Gujarati', name: 'Gujarati' },
  { code: 'Haitian Creole', name: 'Haitian Creole' },
  { code: 'Hakha Chin', name: 'Hakha Chin' },
  { code: 'Hausa', name: 'Hausa' },
  { code: 'Hawaiian', name: 'Hawaiian' },
  { code: 'Hebrew', name: 'Hebrew' },
  { code: 'Hiligaynon', name: 'Hiligaynon' },
  { code: 'Hindi', name: 'Hindi' },
  { code: 'Hmong', name: 'Hmong' },
  { code: 'Hungarian', name: 'Hungarian' },
  { code: 'Hunsrik', name: 'Hunsrik' },
  { code: 'Iban', name: 'Iban' },
  { code: 'Icelandic', name: 'Icelandic' },
  { code: 'Igbo', name: 'Igbo' },
  { code: 'Ilocano', name: 'Ilocano' },
  { code: 'Indonesian', name: 'Indonesian' },
  { code: 'Inuktut (Latin)', name: 'Inuktut (Latin)' },
  { code: 'Inuktut (Syllabics)', name: 'Inuktut (Syllabics)' },
  { code: 'Irish', name: 'Irish' },
  { code: 'Italian', name: 'Italian' },
  { code: 'Jamaican Patois', name: 'Jamaican Patois' },
  { code: 'Japanese', name: 'Japanese' },
  { code: 'Javanese', name: 'Javanese' },
  { code: 'Jingpo', name: 'Jingpo' },
  { code: 'Kalaallisut', name: 'Kalaallisut' },
  { code: 'Kannada', name: 'Kannada' },
  { code: 'Kanuri', name: 'Kanuri' },
  { code: 'Kapampangan', name: 'Kapampangan' },
  { code: 'Kazakh', name: 'Kazakh' },
  { code: 'Khasi', name: 'Khasi' },
  { code: 'Khmer', name: 'Khmer' },
  { code: 'Kiga', name: 'Kiga' },
  { code: 'Kikongo', name: 'Kikongo' },
  { code: 'Kinyarwanda', name: 'Kinyarwanda' },
  { code: 'Kituba', name: 'Kituba' },
  { code: 'Kokborok', name: 'Kokborok' },
  { code: 'Komi', name: 'Komi' },
  { code: 'Konkani', name: 'Konkani' },
  { code: 'Korean', name: 'Korean' },
  { code: 'Krio', name: 'Krio' },
  { code: 'Kurdish (Kurmanji)', name: 'Kurdish (Kurmanji)' },
  { code: 'Kurdish (Sorani)', name: 'Kurdish (Sorani)' },
  { code: 'Kyrgyz', name: 'Kyrgyz' },
  { code: 'Lao', name: 'Lao' },
  { code: 'Latgalian', name: 'Latgalian' },
  { code: 'Latin', name: 'Latin' },
  { code: 'Latvian', name: 'Latvian' },
  { code: 'Ligurian', name: 'Ligurian' },
  { code: 'Limburgish', name: 'Limburgish' },
  { code: 'Lingala', name: 'Lingala' },
  { code: 'Lithuanian', name: 'Lithuanian' },
  { code: 'Lombard', name: 'Lombard' },
  { code: 'Luganda', name: 'Luganda' },
  { code: 'Luo', name: 'Luo' },
  { code: 'Luxembourgish', name: 'Luxembourgish' },
  { code: 'Macedonian', name: 'Macedonian' },
  { code: 'Madurese', name: 'Madurese' },
  { code: 'Maithili', name: 'Maithili' },
  { code: 'Makassar', name: 'Makassar' },
  { code: 'Malagasy', name: 'Malagasy' },
  { code: 'Malay', name: 'Malay' },
  { code: 'Malay (Jawi)', name: 'Malay (Jawi)' },
  { code: 'Malayalam', name: 'Malayalam' },
  { code: 'Maltese', name: 'Maltese' },
  { code: 'Mam', name: 'Mam' },
  { code: 'Manx', name: 'Manx' },
  { code: 'Maori', name: 'Maori' },
  { code: 'Marathi', name: 'Marathi' },
  { code: 'Marshallese', name: 'Marshallese' },
  { code: 'Marwadi', name: 'Marwadi' },
  { code: 'Mauritian Creole', name: 'Mauritian Creole' },
  { code: 'Meadow Mari', name: 'Meadow Mari' },
  { code: 'Meiteilon (Manipuri)', name: 'Meiteilon (Manipuri)' },
  { code: 'Minang', name: 'Minang' },
  { code: 'Mizo', name: 'Mizo' },
  { code: 'Mongolian', name: 'Mongolian' },
  { code: 'Myanmar (Burmese)', name: 'Myanmar (Burmese)' },
  { code: 'Nahuatl (Eastern Huasteca)', name: 'Nahuatl (Eastern Huasteca)' },
  { code: 'Ndau', name: 'Ndau' },
  { code: 'Ndebele (South)', name: 'Ndebele (South)' },
  { code: 'Nepalbhasa (Newari)', name: 'Nepalbhasa (Newari)' },
  { code: 'Nepali', name: 'Nepali' },
  { code: 'NKo', name: 'NKo' },
  { code: 'Norwegian', name: 'Norwegian' },
  { code: 'Nuer', name: 'Nuer' },
  { code: 'Occitan', name: 'Occitan' },
  { code: 'Odia (Oriya)', name: 'Odia (Oriya)' },
  { code: 'Oromo', name: 'Oromo' },
  { code: 'Ossetian', name: 'Ossetian' },
  { code: 'Pangasinan', name: 'Pangasinan' },
  { code: 'Papiamento', name: 'Papiamento' },
  { code: 'Pashto', name: 'Pashto' },
  { code: 'Persian', name: 'Persian' },
  { code: 'Polish', name: 'Polish' },
  { code: 'Portuguese (Brazil)', name: 'Portuguese (Brazil)' },
  { code: 'Portuguese (Portugal)', name: 'Portuguese (Portugal)' },
  { code: 'Punjabi (Gurmukhi)', name: 'Punjabi (Gurmukhi)' },
  { code: 'Punjabi (Shahmukhi)', name: 'Punjabi (Shahmukhi)' },
  { code: 'Quechua', name: 'Quechua' },
  { code: 'Qʼeqchiʼ', name: 'Qʼeqchiʼ' },
  { code: 'Romani', name: 'Romani' },
  { code: 'Romanian', name: 'Romanian' },
  { code: 'Rundi', name: 'Rundi' },
  { code: 'Russian', name: 'Russian' },
  { code: 'Sami (North)', name: 'Sami (North)' },
  { code: 'Samoan', name: 'Samoan' },
  { code: 'Sango', name: 'Sango' },
  { code: 'Sanskrit', name: 'Sanskrit' },
  { code: 'Santali (Latin)', name: 'Santali (Latin)' },
  { code: 'Santali (Ol Chiki)', name: 'Santali (Ol Chiki)' },
  { code: 'Scots Gaelic', name: 'Scots Gaelic' },
  { code: 'Sepedi', name: 'Sepedi' },
  { code: 'Serbian', name: 'Serbian' },
  { code: 'Sesotho', name: 'Sesotho' },
  { code: 'Seychellois Creole', name: 'Seychellois Creole' },
  { code: 'Shan', name: 'Shan' },
  { code: 'Shona', name: 'Shona' },
  { code: 'Sicilian', name: 'Sicilian' },
  { code: 'Silesian', name: 'Silesian' },
  { code: 'Sindhi', name: 'Sindhi' },
  { code: 'Sinhala', name: 'Sinhala' },
  { code: 'Slovak', name: 'Slovak' },
  { code: 'Slovenian', name: 'Slovenian' },
  { code: 'Somali', name: 'Somali' },
  { code: 'Spanish', name: 'Spanish' },
  { code: 'Sundanese', name: 'Sundanese' },
  { code: 'Susu', name: 'Susu' },
  { code: 'Swahili', name: 'Swahili' },
  { code: 'Swati', name: 'Swati' },
  { code: 'Swedish', name: 'Swedish' },
  { code: 'Tahitian', name: 'Tahitian' },
  { code: 'Tajik', name: 'Tajik' },
  { code: 'Tamazight', name: 'Tamazight' },
  { code: 'Tamazight (Tifinagh)', name: 'Tamazight (Tifinagh)' },
  { code: 'Tamil', name: 'Tamil' },
  { code: 'Tatar', name: 'Tatar' },
  { code: 'Telugu', name: 'Telugu' },
  { code: 'Tetum', name: 'Tetum' },
  { code: 'Thai', name: 'Thai' },
  { code: 'Tibetan', name: 'Tibetan' },
  { code: 'Tigrinya', name: 'Tigrinya' },
  { code: 'Tiv', name: 'Tiv' },
  { code: 'Tok Pisin', name: 'Tok Pisin' },
  { code: 'Tongan', name: 'Tongan' },
  { code: 'Tshiluba', name: 'Tshiluba' },
  { code: 'Tsonga', name: 'Tsonga' },
  { code: 'Tswana', name: 'Tswana' },
  { code: 'Tulu', name: 'Tulu' },
  { code: 'Tumbuka', name: 'Tumbuka' },
  { code: 'Turkish', name: 'Turkish' },
  { code: 'Turkmen', name: 'Turkmen' },
  { code: 'Tuvan', name: 'Tuvan' },
  { code: 'Twi', name: 'Twi' },
  { code: 'Udmurt', name: 'Udmurt' },
  { code: 'Ukrainian', name: 'Ukrainian' },
  { code: 'Urdu', name: 'Urdu' },
  { code: 'Uyghur', name: 'Uyghur' },
  { code: 'Uzbek', name: 'Uzbek' },
  { code: 'Venda', name: 'Venda' },
  { code: 'Venetian', name: 'Venetian' },
  { code: 'Vietnamese', name: 'Vietnamese' },
  { code: 'Waray', name: 'Waray' },
  { code: 'Welsh', name: 'Welsh' },
  { code: 'Wolof', name: 'Wolof' },
  { code: 'Xhosa', name: 'Xhosa' },
  { code: 'Yakut', name: 'Yakut' },
  { code: 'Yiddish', name: 'Yiddish' },
  { code: 'Yoruba', name: 'Yoruba' },
  { code: 'Yucatec Maya', name: 'Yucatec Maya' },
  { code: 'Zapotec', name: 'Zapotec' },
  { code: 'Zulu', name: 'Zulu' },
];
